# Linear Algebra

While algorithms for matrix algebra are interesting, they are bit complicated to explore for the computational section of the Mathematical Physics I course.  Here we will rely more on python packages to solve linear algebra problems. One such package that we will introduce is the scipy package, which you will rely extensivley on this module. While matrix operations like matrix multiplication and dot products will be covered, the goal here will be to build up to the method of finite differences and build the intuition on what it means when we say "d/dx" is a linear operator and solve a quantum mechanics problem using your new found computational methods in linear algebra.

Topics:
1. Multidemsional Array and Matrix Operation Basics
2. expand on this section while more topics are added

For some information in the scipy package, it was built on top of the numpy package. It is far more opitmized than numpy for scientific computing. Numpy will handle all our basic functions such as creating arrays and basic operations and scipy will handle the actual matrix algebra.

In [7]:
#as always we import numpy and matplotlib :)
import numpy as np
import matplotlib.pyplot as plt 
from scipy import linalg   #scipy is made of a lot of different modules so we want import the exact ones we want.


## Getting Started with Multidimensional Array Basics
We will be using multidemnsional arrays to represent our matrices, so it's important to know how to work with them.
Let's construct the following matrix using a multidemnsional array:
\begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
1 & 3 & 5
\end{bmatrix}

In [16]:
a = np.array([[1, 2, 3], 
              [2, 4, 6], 
              [1, 3, 5]])   ## I like to write my multidimensional arrays stacked like this to better visualize the outcome.
                            ## not needed to stack, but you should recoginize that it looks more like a matrix this way

In [17]:
a

array([[1, 2, 3],
       [2, 4, 6],
       [1, 3, 5]])

We can perform all the same operations on arrays as before, for example:

In [37]:
b = 2 * a  #every entry is multiplied by 2. Make your own coding cells and play around with it
b

array([[ 2,  4,  6],
       [ 4,  8, 12],
       [ 2,  6, 10]])

It's important to know how arrays are indexed. We can call for a specific rows like this:

In [38]:
b[2]  #again remember that counting starts from 0 so calling a[2] calls the third row of an array since 0 -> 1 -> 2

array([ 2,  6, 10])

For columns we use:

In [79]:
b[:,0]  #':' means to go across all rows but only take the 0th element (so the first column)

array([2, 4, 2])

In [80]:
b[1:,1]  # '1:'means go across the 2nd row and down. ',1' means you only want the 2nd element

array([8, 6])

In [87]:
b[1:,:2]  #'1:' means you only want the the 2nd row and down. ':2' means you only want to take 2 elements

array([[4, 8],
       [2, 6]])

## Matrix Operations
We will perform matrix operations on the following $$ A =
\begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
1 & 3 & 5
\end{bmatrix} $$

Let's imagine the following the vectors: $\vec{b_1} = \begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix}$, $\vec{b_2} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $, and $\vec{b_3} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$ 

Let's start defining the matrix again in a multidimensional array and our vectors which we will use one dimensional arrays :

In [94]:
#matrix A
A = np.array([[1, 2 ,3],
              [2, 4, 6],
              [1, 3, 5]])
#vectors b1, b2 ,b3
b1 = np.array([2, 2, 2])
b2 = np.array([1, 2, 3])
b3 = np.array([1, 0 , 0])

Multiply A by $\vec{b_1}$: $$ A\vec{b_1} =
\begin{bmatrix}
1 & 2 & 3\\
2 & 4 & 6\\
1 & 3 & 5
\end{bmatrix} \begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix} = \begin{bmatrix} 12 \\ 24 \\ 18 \end{bmatrix}  $$

In [98]:
A@b1 

array([12, 24, 18])

To Transpose a matrix, $A^{T} $

In [92]:
A.T

array([[1, 2, 1],
       [2, 4, 3],
       [3, 6, 5]])

To take the dot product $\vec{b_1} \cdot \vec{b_2} $:

In [96]:
np.dot(b1, b2) #so newer version of python include the integer type of the value, you can write print() if this annoys you

np.int64(12)

To take a cross product $\vec{b_1} \times \vec{b_3}$:

In [97]:
np.cross(b1, b3)

array([ 0,  2, -2])

# Solving a System of Equations
We will be using np.linalg.solve(a,b) to solve a system of linear equations. This function computes the exact solution of a well determined nxn matrix. Suppose that we a system of equations in the form: $$x + 2y - z = 4 $$ $$2x  - z = 1 $$ $$x - 2y = -3 $$

Writen in the matrix equation form $A\vec{x}=\vec{b} $ we have:  $$
\begin{bmatrix}
1 & 2 & -1\\
2 & 0 & -1\\
2 & -2 & 0
\end{bmatrix} \begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 4 \\ 1 \\ -3 \end{bmatrix}  $$


In [105]:
#we want to solve for x. We should define A and B in terms of arrays
A = np.array([[1, 2, -1],
              [2, 0, -1],
              [2, -2, 0]])
b= np.array([4, 1, -3])
x = np.linalg.solve(A,b)
x

array([ 0. ,  1.5, -1. ])

In [106]:
# we can easily verify that x is a solution by multiplying the matrix by x
A@x

array([ 4.,  1., -3.])